services:
    tsbby42-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: tsbby42-app
        expose:
            - "3000"
        environment:
            - NODE_ENV=production
            - APP_URL=${APP_URL:?}
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "http://tsbby42-app:3000/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
