services:
    tsbby42-app:
        build:
            context: .
            dockerfile: Dockerfile
        image: tsbby42-app
        ports:
            - "8080:80"
        environment:
            - NODE_ENV=production
            - APP_URL=http://0.0.0.0:80
        healthcheck:
            test: ["CMD", "wget", "--spider", "-q", "http://tsbby42-app:80/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s
