name: CI

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read

        strategy:
            matrix:
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
                node-version: [24.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup pnpm
              uses: pnpm/action-setup@v4

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "pnpm"

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Lint
              run: pnpm lint

            - name: Test
              run: pnpm test

            - name: Build
              run: pnpm build
